# Generated by Django 4.2.4 on 2023-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="id_number",
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="NA", max_length=100),
            preserve_default=False,
        ),
    ]
