# Generated by Django 4.2.4 on 2023-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_student_id_number_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
