# Generated by Django 4.2.4 on 2023-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_app", "0003_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Guardian", "Guardian"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
